package com.nis2ready.audit;

public enum AuditEventType {
  USER_REGISTERED,
  LOGIN_SUCCEEDED,
  LOGIN_FAILED,
  ORGANIZATION_UPDATED,
  MEMBER_INVITED,
  ASSESSMENT_CREATED,
  ASSESSMENT_COMPLETED,
  EVIDENCE_UPLOADED,
  EVIDENCE_DOWNLOADED,
  EVIDENCE_STATUS_CHANGED,
  EVIDENCE_DELETED,
  TASK_CREATED,
  TASK_UPDATED,
  TASK_DELETED
}
